name: Build agenda PDF
on:
  workflow_dispatch:
  push:
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet run
      - uses: actions/upload-artifact@v4
        with:
          name: Preview_Agenda
          path: Preview_Agenda.pdf
